### ISSUE TITLE
[Question] Is external volumes still needed when using this ?

### ISSUE THREAD

**Issue by blmhemu** [pteich/caddy-tlsconsul#25]
```
Caddy requires write access to two locations: a data directory, and a configuration directory.
While it's not necessary to persist the files stored in the configuration directory, it can be convenient. 
However, it's very important to persist the data directory.
```
The above snippet is from caddy docker readme.

Does this plugin make both these storage requirements redundant ?

**Comment by pteich** [comment]
With this plugin all data regarding certificates is saved in Consul's KV storage. You need to provide a Caddyfile that needs to be stored somewhere. But I am not aware of any other data that needs to be stored in a persistent way.
At least I use Caddy with this plugin only for years now without mounting additional volumes to my Caddy Docker container.
