### ISSUE TITLE
[Question] I was wondering if this plugin integrates with CDP ?

### ISSUE THREAD

**Issue by eazylaykzy** [pteich/caddy-tlsconsul#31]
Thanks for this great module, I was wondering if it integrates with [CDP](https://github.com/lucaslorentz/caddy-docker-proxy), I'm planning to use both in a Docker-Swarm mode environment, but I'm finding it hard to put things together, there are no pointers, I will appreciate any assistance.

**Comment by pteich** [comment]
It seems that CDP just dynamically creates a Caddyfile based on Docker data but uses a Caddy as is and does not include it's own version. So if you use a Caddy binary that enables this plugin (or any other plugin) it should just work.

**Comment by eazylaykzy** [comment]
@pteich Thanks, I currently use CDP as it is and works fine as I no longer require Consul in my setup.

Great plugin between, I will go ahead and close this issue/discussion.
