### ISSUE TITLE
storage module 'caddy.storage.tlsconsul' is not a Caddyfile unmarshaler

### ISSUE THREAD

**Issue by louis-lau** [pteich/caddy-tlsconsul#9]
Got the docker image and added the configuration option as suggested in the readme. But I get `storage module 'caddy.storage.tlsconsul' is not a Caddyfile unmarshaler`. Any suggestions?

Thanks

**Comment by pteich** [comment]
I'll have a look at this. I think I already have an idea what's missing.

**Comment by mholt** [comment]
This page should be of assistance: https://caddyserver.com/docs/extending-caddy/caddyfile -- it's just one method :)

**Comment by pteich** [comment]
Ah thanks, that was what I had in mind @mholt ;)
